version: "2"
services:
  django:
    build: ./django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./django/.env
    depends_on:
      - postgres

  postgres:
    build: ./postgres
    volumes:
      - sample_postgis_data:/var/lib/postgresql/data
      - ./postgres/sql:/docker-entrypoint-initdb.d
    env_file: ./postgres/.env_db
    ports:
      - 5433:5432

  nginx:
    build: ./nginx
    volumes:
      - ./django/static:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  sample_postgis_data: